title: Ali Baba Tajine
tagline: Das Original
author:
  name: Ali Baba Tajine
  email: github@tajine.de
  github: consolacao
  twitter: alibabatajine
  
url:
baseurl:
production_url:
permalink: /:categories/:title.html
relative_permalinks: false
encoding: utf-8

timezone: Germany/Munich
future: true
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

jekyll_timeago:
  depth: 2 # Level of detail
  today: 'Heute'
  yesterday: 'Gestern'
  tomorrow: 'Morgen'
  and: 'und'
  suffix: ''
  prefix: 'vor'
  suffix_future: 'in'
  prefix_future: ''
  years: 'Jahren'
  year: 'Jahr'
  months: 'Monaten'
  month: 'Monat'
  weeks: 'Wochen'
  week: 'Woche'
  days: 'Tagen'
  day: 'Tag'
  
  
include: [".htaccess"]
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md", "node_modules", "OLD_SITE", "SQL", "Ali-Baba-Tajine.github.io.esproj", "_to_integrate", "Z_ORIGINAL_BACKUP", "3D_MODELLE", "Gruntfile.js", "assets_not_used", "SICHERUNGEN", "epub", "Rakefile.rb", "TRASHCAN", "package.json", "jekyll-navigation.gemspec", "parse", "minify.sh", "config", "sass_default"]
  
  